apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: <<Name space donde se realizará el monitoreo>>
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_always_on
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
#  nodejs:
#    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
#  python:
#    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
